# Step 1:Regressor:


In [1]:
# importing the library for assignemt

In [2]:
# importing the labraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sn

In [3]:
# Import data set

df = pd.read_csv("weight-height.csv") 
df

Gender     Height      Weight
0       Male  73.847017  241.893563
1       Male  68.781904  162.310473
2       Male  74.110105  212.740856
3       Male  71.730978  220.042470
4       Male  69.881796  206.349801
...      ...        ...         ...
8550  Female  60.483946  110.565497
8551  Female  63.423372  129.921671
8552  Female  65.584057  155.942671
8553  Female  67.429971  151.678405
8554  Female  60.921791  131.253738

[8555 rows x 3 columns]

In [4]:
df['Gender'] = df['Gender'].astype('category')
df['Gender'] = df['Gender'].cat.codes
df

Gender     Height      Weight
0          1  73.847017  241.893563
1          1  68.781904  162.310473
2          1  74.110105  212.740856
3          1  71.730978  220.042470
4          1  69.881796  206.349801
...      ...        ...         ...
8550       0  60.483946  110.565497
8551       0  63.423372  129.921671
8552       0  65.584057  155.942671
8553       0  67.429971  151.678405
8554       0  60.921791  131.253738

[8555 rows x 3 columns]

In [5]:
df.isnull().sum()

Gender    0
Height    0
Weight    0
dtype: int64

In [6]:
#Separate x(Gender, Height) and y (y=Weight)

x = df.drop(columns = 'Weight')
x

Gender     Height
0          1  73.847017
1          1  68.781904
2          1  74.110105
3          1  71.730978
4          1  69.881796
...      ...        ...
8550       0  60.483946
8551       0  63.423372
8552       0  65.584057
8553       0  67.429971
8554       0  60.921791

[8555 rows x 2 columns]

In [7]:
y = df[['Weight']]
y

Weight
0     241.893563
1     162.310473
2     212.740856
3     220.042470
4     206.349801
...          ...
8550  110.565497
8551  129.921671
8552  155.942671
8553  151.678405
8554  131.253738

[8555 rows x 1 columns]

In [8]:
# important library
from sklearn.model_selection import train_test_split

In [9]:
#Train = 70%, Test = 30%
#separate kora xtrain and ytrain # ranom state data fixed kore ,# testing data 30%

xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size =0.3,random_state =1) 

In [10]:
xtrain.head()

Gender     Height
1277       1  72.385301
5361       0  60.960147
5728       0  69.119292
4276       1  68.271050
3112       1  64.991405

In [11]:
ytrain.head()

Weight
1277  189.165592
5361  124.876796
5728  168.864403
4276  172.941248
3112  144.551044

In [12]:
#Apply Linear Regression

In [13]:
from sklearn.linear_model import LinearRegression # https://scikit-learn.org/stable/

In [14]:
lr =  LinearRegression() ## fit kora mane holo training kora # eita holo object for lr r 

In [15]:
lr.fit(xtrain,ytrain) # training data dia fit korte hobe model 

LinearRegression()

In [16]:
m = lr.coef_ # coef- that means-M slope # coef feature joto golu oita same hobe
m

array([[19.34359322,  5.96887438]])

In [17]:
c = lr.intercept_   # intercept that means- c  in y
c

array([-244.55280903])

In [18]:
#y = mx+c

In [19]:
#ypre = m1*x1+ m2x2+c # x=72.385301 high value

ypre = 19.34359322*1+5.96887438*72.385301+-244.5528090325578
ypre  

206.84955281493055

In [20]:
ypre = 19.34359322*1+5.96887438*68.781904+-244.5528090325578
ypre  

185.3413287806617

In [21]:
lr.predict([[1, 72.385301]])

C:\Users\personal\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[206.84955312]])

In [22]:
lr.predict([[1, 68.781904]])

C:\Users\personal\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[185.34132907]])

In [23]:
df['predicted_weight'] = lr.predict(x)

In [24]:
df

Gender     Height      Weight  predicted_weight
0          1  73.847017  241.893563        215.574352
1          1  68.781904  162.310473        185.341329
2          1  74.110105  212.740856        217.144694
3          1  71.730978  220.042470        202.943984
4          1  69.881796  206.349801        191.906445
...      ...        ...         ...               ...
8550       0  60.483946  110.565497        116.468265
8551       0  63.423372  129.921671        134.013329
8552       0  65.584057  155.942671        146.910187
8553       0  67.429971  151.678405        157.928220
8554       0  60.921791  131.253738        119.081708

[8555 rows x 4 columns]

In [25]:
df.head()

Gender     Height      Weight  predicted_weight
0       1  73.847017  241.893563        215.574352
1       1  68.781904  162.310473        185.341329
2       1  74.110105  212.740856        217.144694
3       1  71.730978  220.042470        202.943984
4       1  69.881796  206.349801        191.906445

In [26]:
#Evaluate the Model (Testing and training Accuracy, MSE for testing) # accuracy dependent on testing data

lr.score(xtest,ytest) 

0.9059959607091161

In [27]:
from sklearn.metrics import mean_squared_error, r2_score

In [28]:
pre = lr.predict(xtest)
pre

array([[143.83013436],
       [197.53417989],
       [184.63515112],
       ...,
       [160.7078525 ],
       [186.82852694],
       [201.4226542 ]])

In [29]:
mean_squared_error(ytest,pre)

99.67250998070031

In [30]:
r2_score(ytest,pre)

0.9059959607091161

In [31]:
#The linear regression model accuracy is 0.9059959607091161

# Apply KNN Regressor

In [32]:
from sklearn.neighbors import KNeighborsRegressor

In [33]:
knn = KNeighborsRegressor(n_neighbors=100)

In [34]:
#Evaluate the Model (Testing and training Accuracy, MSE for testing)
knn.fit(xtrain, ytrain)

KNeighborsRegressor(n_neighbors=100)

In [35]:
pre2= knn.predict(xtest)

In [36]:
mean_squared_error(ytest,pre2)

104.01856360504236

In [37]:
r2_score(ytest,pre2)

0.9018970712987657

In [38]:
#the knn regressor model accuracy is 0.9018970712987657

# KNN Classifier:
    

In [39]:
# Import data set
df 

Gender     Height      Weight  predicted_weight
0          1  73.847017  241.893563        215.574352
1          1  68.781904  162.310473        185.341329
2          1  74.110105  212.740856        217.144694
3          1  71.730978  220.042470        202.943984
4          1  69.881796  206.349801        191.906445
...      ...        ...         ...               ...
8550       0  60.483946  110.565497        116.468265
8551       0  63.423372  129.921671        134.013329
8552       0  65.584057  155.942671        146.910187
8553       0  67.429971  151.678405        157.928220
8554       0  60.921791  131.253738        119.081708

[8555 rows x 4 columns]

In [50]:
#Separate x and (y=Gender)
x = df.drop('Gender', axis=1)
y = df[['Gender']]

In [51]:
x

Height      Weight  predicted_weight
0     73.847017  241.893563        215.574352
1     68.781904  162.310473        185.341329
2     74.110105  212.740856        217.144694
3     71.730978  220.042470        202.943984
4     69.881796  206.349801        191.906445
...         ...         ...               ...
8550  60.483946  110.565497        116.468265
8551  63.423372  129.921671        134.013329
8552  65.584057  155.942671        146.910187
8553  67.429971  151.678405        157.928220
8554  60.921791  131.253738        119.081708

[8555 rows x 3 columns]

In [67]:
x= df.drop('predicted_weight',axis=1)
x

Gender     Height      Weight
0          1  73.847017  241.893563
1          1  68.781904  162.310473
2          1  74.110105  212.740856
3          1  71.730978  220.042470
4          1  69.881796  206.349801
...      ...        ...         ...
8550       0  60.483946  110.565497
8551       0  63.423372  129.921671
8552       0  65.584057  155.942671
8553       0  67.429971  151.678405
8554       0  60.921791  131.253738

[8555 rows x 3 columns]

In [69]:
#Train = 70%, Test = 30%
#separate kora xtrain and ytrain # ranom state data fixed kore ,# testing data 30%

xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size =0.3,random_state =1) 

In [70]:
xtrain.head()

Gender     Height      Weight
1277       1  72.385301  189.165592
5361       0  60.960147  124.876796
5728       0  69.119292  168.864403
4276       1  68.271050  172.941248
3112       1  64.991405  144.551044

In [71]:
ytrain.head()

Gender
1277       1
5361       0
5728       0
4276       1
3112       1

In [72]:
#https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KNeighborsClassifier.html
#Apply KNN Classifier 
from sklearn.neighbors import KNeighborsClassifier
knn2 = KNeighborsClassifier()

In [73]:
knn_cls = KNeighborsClassifier(n_neighbors=100)


In [74]:
knn_cls.fit(xtrain, ytrain)
    

C:\Users\personal\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier(n_neighbors=100)

In [75]:
#Evaluate the Model by only Accuracy.
pre3= knn_cls.predict(xtest)

C:\Users\personal\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


In [76]:
mean_squared_error(ytest,pre3)

0.06973120373977405

In [78]:
r2_score(ytest,pre3)

0.711945510168259

In [79]:
#https://scikit-learn.org/stable/modules/generated/sklearn.metrics.accuracy_score.html

from sklearn.metrics import accuracy_score

In [80]:
accuracy = accuracy_score(ytest, pre3)

In [81]:
accuracy

0.930268796260226

In [ ]:
#Finish